### ISSUE TITLE
Add industry total wages index to read_payrolls

### ISSUE THREAD

**Issue by martintburgess** [MattCowgill/readabs#177]
Hi @MattCowgill, 

Thanks for all your work on this. 

I think we are missing one sheet from the payrolls data in the `read_payrolls` function - Table 4 has a second sheet "Total wages index". 

I think it is a relatively straightforward fix to add into the existing function, I will have a quick go at that now and then send you a PR. 

cc @daviddiviny 

Many thanks,
Martin

**Comment by MattCowgill** [comment]
Thanks @martintburgess - I did actually have that in there at one point as an option, I think I dropped it because the ABS said they were going to stop publishing the wages totals, but then backtracked on that. 

Sure, if you don't mind submitting a PR that'd be great. The `series` column in the returned tibble should read `wages` obviously. Thanks

**Comment by martintburgess** [comment]
Thanks @MattCowgill, I think code to swap the `series` column to `wages` is still there from the previous version so it's a very simple fix.
