### ISSUE TITLE
Spec questions about local files

### ISSUE THREAD

**Issue by HughParsonage** [MattCowgill/readabs#51]
Just some questions about the design. Trying to understand which parts are intended as opposed to documented but potentially changeable.

### What is the purpose of the `filenames` argument? 

Is it purely for performance? It makes sense to include the ability to read in files discretely, but it also seems difficult to work out which filenames I would want to read as opposed to just reading in the whole collection and filtering/selecting in R. 

### Why does `filenames` (silently) refuse a path specification?
https://github.com/MattCowgill/readabs/blob/1e8b37eadc7de6b16ee9dc61a24ff7bcc0b41e66/R/read_abs_local.R#L100

If we omit simply omit this line, a user can provide, say `read_abs_local(filenames = "~/Downloads/6202.0/6202001.xls")` without providing `path`. Or they can provide both and have filenames be relative to `path`: `read_abs_local(path = "~/Downloads/", filenames = "6202.0/6202001.xls")`. The latter form is particularly convenient when `path` is left to its default value.

Obviously the 'normal' use is that `filenames` is relative to path, so `filenames` is identical to `basename(filenames)` but I wonder why this line was required.

### More generally, how much flexibility should `read_abs_local()` provide?

For example, in the latest release's vignette, we have

```r
lfs_local_2 <- read_abs_local(filenames = c("6202001.xls", "6202005.xls"),
                            path = "data/ABS/6202.0")
``` 

The correct argument to `path` in this case seems a bit difficult to get right. Further, it might be redundant because the `readabs` package 'should know' where these files are (or at least where they should be). From my perspective it would seem more convenient for `path` to match the same argument in `read_abs`. One could implement such convenience by asking `read_abs_local` to look in `path` and its subdirectories, but it seems based on the vignette that you chose to not look in the subdirectories.

**Comment by MattCowgill** [comment]
1. My initial idea was that `read_abs_local()` should be able to handle any ABS time series spreadsheet that the user had on disk, even if the file had not been downloaded by `read_abs()`. This might mean that the files have some arbitrary names. I no longer think this is an important use case - we can lose this argument.

2. I don't recall and I'm fine to change this.

3. I agree.

In general, I have given `read_abs_local()` less attention than `read_abs()`. It's likely that quirks reflect casual and/or accidental choices rather than deliberate and well-thought-out design.
