### ISSUE TITLE
Importing ABS trend data using read_abs() returns NAs

### ISSUE THREAD

**Issue by ch3lle82** [MattCowgill/readabs#75]
Hello
I am trying to import multiple ABS trend series (e.g. A84423111V, A84423112W, A84423113X) using the read_abs() function, which returns NA values. This is the case whether I use read_abs() by series_id or cat_no and tables. For example, if you import the preliminary labour force survey (cat_no = "6202.0"), all the trend variables have NA values. Is this something you have come across before?
Thanks
Michelle

**Comment by MattCowgill** [comment]
Hi Michelle,
The ABS has suspended publication of trend series due to COVID-19. See: https://www.abs.gov.au/ausstats/abs@.nsf/Latestproducts/6202.0Main%20Features25Apr%202020?opendocument&tabname=Summary&prodno=6202.0&issue=Apr%202020&num=&view=

This means that however you get your ABS data - from the website, using readabs, or some other means - the trend series will be NA for the time being.
